services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - homer:/www/assets
    ports:
      - 8080:80
    user: 1000:1000
    environment:
      - INIT_ASSETS=1 # default
    restart:
      always
volumes:
  homer: